export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Job {
  id: string;
  date_posted?: string;
  date_created?: string;
  title?: string;
  organization?: string;
  organization_url?: string;
  date_validthrough?: string;
  locations_raw?: string;
  locations_alt_raw?: string;
  location_type?: string;
  location_requirements_raw?: string;
  salary_raw?: string;
  employment_type?: string;
  url?: string;
  source_type?: string;
  source?: string;
  source_domain?: string;
  organization_logo?: string;
  cities_derived?: Json;
  counties_derived?: Json;
  regions_derived?: Json;
  countries_derived?: Json;
  locations_derived?: Json;
  timezones_derived?: Json;
  lats_derived?: Json;
  lngs_derived?: Json;
  remote_derived?: boolean;
  domain_derived?: string;
  recruiter_name?: string;
  recruiter_title?: string;
  recruiter_url?: string;
  linkedin_org_employees?: number;
  linkedin_org_url?: string;
  linkedin_org_size?: string;
  linkedin_org_slogan?: string;
  linkedin_org_industry?: string;
  linkedin_org_followers?: number;
  linkedin_org_headquarters?: string;
  linkedin_org_type?: string;
  linkedin_org_foundeddate?: string;
  linkedin_org_specialties?: Json;
  linkedin_org_locations?: Json;
  linkedin_org_description?: string;
  linkedin_org_slug?: string;
  linkedin_org_recruitment_agency_derived?: boolean;
  seniority?: string;
  directapply?: boolean;
  no_jb_schema?: boolean;
  external_apply_url?: string;
  ats_duplicate?: boolean;
  description_text?: string;
  ai_salary_currency?: string;
  ai_salary_value?: number;
  ai_salary_minvalue?: number;
  ai_salary_maxvalue?: number;
  ai_salary_unittext?: string;
  ai_benefits?: Json;
  ai_experience_level?: string;
  ai_work_arrangement?: string;
  ai_work_arrangement_office_days?: number;
  ai_remote_location?: string;
  ai_remote_location_derived?: string;
  ai_key_skills?: Json;
  ai_hiring_manager_name?: string;
  ai_hiring_manager_email_address?: string;
  ai_core_responsibilities?: string;
  ai_requirements_summary?: string;
  ai_working_hours?: string;
  ai_employment_type?: string;
  ai_job_language?: string;
  ai_visa_sponsorship?: string;
  ai_keywords?: Json;
  ai_taxonomies_a?: Json;
  ai_education_requirements?: string;
  // Handling dotted headers as potential JSONB paths or flattened columns
  'output.scores.role_fit'?: number;
  'output.scores.company_fit'?: number;
  'output.scores.location_flexibility'?: number;
  'output.scores.industry_domain'?: number;
  'output.scores.growth_potential'?: number;
  'output.reasoning.role_fit'?: string;
  'output.reasoning.company_fit'?: string;
  'output.reasoning.location_flexibility'?: string;
  'output.reasoning.industry_domain'?: string;
  'output.reasoning.growth_potential'?: string;
  output_weighted_score?: number; // assuming snake_case if flattened
  output_summary?: string;
  output_verdict?: string;
  output?: Json;
  uuid?: string;
  user_name?: string;
  user_email?: string;
  linkedin_id?: string;
}
