-- =============================================
-- Job Radar: Migrate score columns from 1-10 to 1-100 scale
-- =============================================
-- n8n evaluation pipeline was updated to output integer scores 1-100.
-- The DB had a mix of old 1-10 rows and newer 1-100 rows (inline constraint
-- names were auto-generated by Postgres, so named DROP failed silently).

-- Step 1: Drop ALL score-related check constraints by scanning their definitions
-- (handles auto-generated names from the original migration)
DO $$
DECLARE
  r RECORD;
BEGIN
  FOR r IN
    SELECT tc.constraint_name
    FROM information_schema.table_constraints tc
    JOIN information_schema.check_constraints cc USING (constraint_name)
    WHERE tc.table_name = 'evaluations'
      AND tc.constraint_type = 'CHECK'
      AND cc.check_clause LIKE '%score%'
  LOOP
    EXECUTE 'ALTER TABLE evaluations DROP CONSTRAINT "' || r.constraint_name || '"';
  END LOOP;
END $$;

-- Step 2: Convert to INTEGER with safe clamping to 1-100.
-- CASE: value > 10 means already on 1-100 scale; else multiply by 10.
-- GREATEST/LEAST: hard-clamp so no row can violate the new constraint.
ALTER TABLE evaluations
  ALTER COLUMN score_total   TYPE INTEGER USING GREATEST(1, LEAST(100,
    CASE WHEN score_total   > 10 THEN ROUND(score_total)::INTEGER   ELSE ROUND(score_total   * 10)::INTEGER END)),
  ALTER COLUMN score_role    TYPE INTEGER USING GREATEST(1, LEAST(100,
    CASE WHEN score_role    > 10 THEN ROUND(score_role)::INTEGER    ELSE ROUND(score_role    * 10)::INTEGER END)),
  ALTER COLUMN score_company TYPE INTEGER USING GREATEST(1, LEAST(100,
    CASE WHEN score_company > 10 THEN ROUND(score_company)::INTEGER ELSE ROUND(score_company * 10)::INTEGER END)),
  ALTER COLUMN score_location TYPE INTEGER USING GREATEST(1, LEAST(100,
    CASE WHEN score_location > 10 THEN ROUND(score_location)::INTEGER ELSE ROUND(score_location * 10)::INTEGER END)),
  ALTER COLUMN score_industry TYPE INTEGER USING GREATEST(1, LEAST(100,
    CASE WHEN score_industry > 10 THEN ROUND(score_industry)::INTEGER ELSE ROUND(score_industry * 10)::INTEGER END)),
  ALTER COLUMN score_growth  TYPE INTEGER USING GREATEST(1, LEAST(100,
    CASE WHEN score_growth  > 10 THEN ROUND(score_growth)::INTEGER  ELSE ROUND(score_growth  * 10)::INTEGER END));

-- Step 3: Add named 1-100 CHECK constraints
ALTER TABLE evaluations ADD CONSTRAINT evaluations_score_total_check
  CHECK (score_total >= 1 AND score_total <= 100);
ALTER TABLE evaluations ADD CONSTRAINT evaluations_score_role_check
  CHECK (score_role >= 1 AND score_role <= 100);
ALTER TABLE evaluations ADD CONSTRAINT evaluations_score_company_check
  CHECK (score_company >= 1 AND score_company <= 100);
ALTER TABLE evaluations ADD CONSTRAINT evaluations_score_location_check
  CHECK (score_location >= 1 AND score_location <= 100);
ALTER TABLE evaluations ADD CONSTRAINT evaluations_score_industry_check
  CHECK (score_industry >= 1 AND score_industry <= 100);
ALTER TABLE evaluations ADD CONSTRAINT evaluations_score_growth_check
  CHECK (score_growth >= 1 AND score_growth <= 100);
